// Central list of allowed player titles.
// Add new titles here without touching the Player model.

module.exports = [
  "New gun on the block",
  "Rookie",
  "War agent",
  "Alcholic",
  "Billionaire",
  "Trillionaire",
  "Tycoon",
  "Developer",
  "Admin",
  "Moderator",
  "DevBox 360",
  "Alcholic",
  "Drugy McDrugface",
  "The Collector",
  "Master of Mayhem",
  "Lord of the Flies",
  "Schrute Farms's Finest",
  "Jim",
  "Trader",
  "The Investor",
  "Diamond Hands",
  "Inbecile",
  "Nerd",
  "Unlucky",
  "Nudist",
  "Cleptomaniac",
  "Couch Potato",
  "Fashionista",
  "Gamer",
  "Bookworm",
  "Kingpin",
  "Drug Lord",
  "Cartel Boss",
  "Underboss",
  "Capo",
  "Enforcer",
  "Hitman",
  "Money Launderer",
  "Smuggler",
  "Drug Mule",
  "Street Dealer",
  "Gangster",
  "Mobster",
  "Outlaw",
  "Rebel",
  "Renegade",
  "Vigilante"
];
